# Generated by Django 4.2 on 2024-03-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_order_dni"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="address1",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="address2",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="date_modified",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="state",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="zipcode",
        ),
    ]
