# Generated by Django 4.2 on 2024-04-01 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_delete_customer_remove_profile_address1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
